// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };


type PickContentRelationshipFieldData<
	TRelationship extends prismic.CustomTypeModelFetchCustomTypeLevel1 | prismic.CustomTypeModelFetchCustomTypeLevel2 | prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<string, prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone>,
	TLang extends string
> = |
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship["id"]]:
			ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
	} &
	// Group
	{
		[TGroup in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup["id"]]:
			TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
				? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
				: never
	} &
	// Other fields
	{
		[TFieldKey in Extract<TRelationship["fields"][number], string>]:
			TFieldKey extends keyof TData ? TData[TFieldKey] : never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[] | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>["id"]]:
		prismic.ContentRelationshipField<
			ID,
			TLang,
			PickContentRelationshipFieldData<
				Extract<TCustomType[number], { id: ID }>,
				Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
				TLang
			>
		>
}[Exclude<TCustomType[number], string>["id"]];

type ContentPageDocumentDataHeadingSlice = PageTitleSlice | BreadcrumbsSlice | HeroBannerSlice

type ContentPageDocumentDataMainSlice = CtaBannerSlice | FaqQuestionListSlice | RichTextSectionSlice | InfoCardListSlice | ImageBlockSlice | ButtonLinkSlice | CalloutSlice | AccordionSlice | DisclosureListSlice | FileDownloadListSlice

type ContentPageDocumentDataAsideSlice = CtaBannerSlice | FaqQuestionListSlice

type ContentPageDocumentDataFooterSlice = NewsletterSignupSlice | SocialLinksSlice

/**
 * Content for Content Page documents
 */
interface ContentPageDocumentData {
	/**
	 * Breadcrumb Level 1 Label field in *Content Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_page.breadcrumb_level_1_label
	 * - **Tab**: Heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	breadcrumb_level_1_label: prismic.KeyTextField;
	
	/**
	 * Breadcrumb Level 1 Href field in *Content Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_page.breadcrumb_level_1_href
	 * - **Tab**: Heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	breadcrumb_level_1_href: prismic.KeyTextField;
	
	/**
	 * Breadcrumb Level 2 Label field in *Content Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_page.breadcrumb_level_2_label
	 * - **Tab**: Heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	breadcrumb_level_2_label: prismic.KeyTextField;
	
	/**
	 * Breadcrumb Level 2 Href field in *Content Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_page.breadcrumb_level_2_href
	 * - **Tab**: Heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	breadcrumb_level_2_href: prismic.KeyTextField;
	
	/**
	 * Breadcrumb Level 3 Label field in *Content Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_page.breadcrumb_level_3_label
	 * - **Tab**: Heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	breadcrumb_level_3_label: prismic.KeyTextField;
	
	/**
	 * Breadcrumb Level 3 Href field in *Content Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_page.breadcrumb_level_3_href
	 * - **Tab**: Heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	breadcrumb_level_3_href: prismic.KeyTextField;
	
	/**
	 * Heading Slice Zone field in *Content Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_page.heading[]
	 * - **Tab**: Heading
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	heading: prismic.SliceZone<ContentPageDocumentDataHeadingSlice>;/**
	 * Main Slice Zone field in *Content Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_page.main[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	main: prismic.SliceZone<ContentPageDocumentDataMainSlice>;/**
	 * Aside Slice Zone field in *Content Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_page.aside[]
	 * - **Tab**: Aside
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	aside: prismic.SliceZone<ContentPageDocumentDataAsideSlice>;/**
	 * Footer Slice Zone field in *Content Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_page.footer[]
	 * - **Tab**: Footer
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	footer: prismic.SliceZone<ContentPageDocumentDataFooterSlice>;
}

/**
 * Content Page document from Prismic
 *
 * - **API ID**: `content_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContentPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<ContentPageDocumentData>, "content_page", Lang>;

export type AllDocumentTypes = ContentPageDocument;

/**
 * Primary content in *Accordion → Items*
 */
export interface AccordionSliceDefaultItem {
	/**
	 * Title field in *Accordion → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordion.items[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Highlighted Note field in *Accordion → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordion.items[].note
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	note: prismic.KeyTextField;
	
	/**
	 * Body field in *Accordion → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordion.items[].body
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField;
	
	/**
	 * Necessities Heading field in *Accordion → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordion.items[].necessities_heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	necessities_heading: prismic.KeyTextField;
	
	/**
	 * Necessities field in *Accordion → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordion.items[].necessities
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	necessities: prismic.RichTextField;
	
	/**
	 * Link Label field in *Accordion → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordion.items[].link_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	link_label: prismic.KeyTextField;
	
	/**
	 * Link field in *Accordion → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordion.items[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Second Link Label field in *Accordion → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordion.items[].link2_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	link2_label: prismic.KeyTextField;

	/**
	 * Second Link field in *Accordion → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordion.items[].link2
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link2: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Accordion Slice
 *
 * - **API ID**: `default`
 * - **Description**: Numbered accordion items
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AccordionSliceDefault = prismic.SharedSliceVariation<"default", Record<string, never>, Simplify<AccordionSliceDefaultItem>>;

/**
 * Slice variation for *Accordion*
 */
type AccordionSliceVariation = AccordionSliceDefault

/**
 * Accordion Shared Slice
 *
 * - **API ID**: `accordion`
 * - **Description**: Numbered, individually collapsible sections (e.g. a step-by-step process)
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AccordionSlice = prismic.SharedSlice<"accordion", AccordionSliceVariation>;

/**
 * Primary content in *DisclosureList → Items*
 */
export interface DisclosureListSliceDefaultItem {
	/**
	 * Title field in *DisclosureList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: disclosure_list.items[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Body field in *DisclosureList → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: disclosure_list.items[].body
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField;

	/**
	 * Box Heading field in *DisclosureList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: disclosure_list.items[].box_heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	box_heading: prismic.KeyTextField;

	/**
	 * Box Body field in *DisclosureList → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: disclosure_list.items[].box_body
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	box_body: prismic.RichTextField;

	/**
	 * Link Label field in *DisclosureList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: disclosure_list.items[].link_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	link_label: prismic.KeyTextField;

	/**
	 * Link field in *DisclosureList → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: disclosure_list.items[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for DisclosureList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Toggleable sections
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DisclosureListSliceDefault = prismic.SharedSliceVariation<"default", Record<string, never>, Simplify<DisclosureListSliceDefaultItem>>;

/**
 * Slice variation for *DisclosureList*
 */
type DisclosureListSliceVariation = DisclosureListSliceDefault

/**
 * DisclosureList Shared Slice
 *
 * - **API ID**: `disclosure_list`
 * - **Description**: Unnumbered collapsible sections, each with an optional highlighted box and link (e.g. eligibility/policy details)
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DisclosureListSlice = prismic.SharedSlice<"disclosure_list", DisclosureListSliceVariation>;

/**
 * Primary content in *FileDownloadList → Items*
 */
export interface FileDownloadListSliceDefaultItem {
	/**
	 * Button Label field in *FileDownloadList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: file_download_list.items[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;

	/**
	 * File field in *FileDownloadList → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: file_download_list.items[].file
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	file: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * File Size field in *FileDownloadList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: e.g. 504KB
	 * - **API ID Path**: file_download_list.items[].file_size
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	file_size: prismic.KeyTextField;
}

/**
 * Default variation for FileDownloadList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Download buttons with file size
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FileDownloadListSliceDefault = prismic.SharedSliceVariation<"default", Record<string, never>, Simplify<FileDownloadListSliceDefaultItem>>;

/**
 * Slice variation for *FileDownloadList*
 */
type FileDownloadListSliceVariation = FileDownloadListSliceDefault

/**
 * FileDownloadList Shared Slice
 *
 * - **API ID**: `file_download_list`
 * - **Description**: A row of outline download buttons, each with a label and file size caption (e.g. downloadable PDF forms)
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FileDownloadListSlice = prismic.SharedSlice<"file_download_list", FileDownloadListSliceVariation>;

/**
 * Primary content in *Breadcrumbs → Default → Primary*
 */
export interface BreadcrumbsSliceDefaultPrimary {
	/**
	 * Separator field in *Breadcrumbs → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: /
	 * - **API ID Path**: breadcrumbs.default.primary.separator
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	separator: prismic.KeyTextField;
}

/**
 * Default variation for Breadcrumbs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BreadcrumbsSliceDefault = prismic.SharedSliceVariation<"default", Simplify<BreadcrumbsSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Breadcrumbs*
 */
type BreadcrumbsSliceVariation = BreadcrumbsSliceDefault

/**
 * Breadcrumbs Shared Slice
 *
 * - **API ID**: `breadcrumbs`
 * - **Description**: Breadcrumbs
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BreadcrumbsSlice = prismic.SharedSlice<"breadcrumbs", BreadcrumbsSliceVariation>;

/**
 * Primary content in *ButtonLink → Default → Primary*
 */
export interface ButtonLinkSliceDefaultPrimary {
	/**
	 * Label field in *ButtonLink → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: button_link.default.primary.label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * Link field in *ButtonLink → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: button_link.default.primary.link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for ButtonLink Slice
 *
 * - **API ID**: `default`
 * - **Description**: Centered outline button
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ButtonLinkSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ButtonLinkSliceDefaultPrimary>, never>;

/**
 * Slice variation for *ButtonLink*
 */
type ButtonLinkSliceVariation = ButtonLinkSliceDefault

/**
 * ButtonLink Shared Slice
 *
 * - **API ID**: `button_link`
 * - **Description**: A single centered outline button linking to another page
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ButtonLinkSlice = prismic.SharedSlice<"button_link", ButtonLinkSliceVariation>;

/**
 * Primary content in *Callout → Default → Primary*
 */
export interface CalloutSliceDefaultPrimary {
	/**
	 * Style field in *Callout → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Neutral
	 * - **API ID Path**: callout.default.primary.style
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	style: prismic.SelectField<"Neutral" | "Info" | "Warning" | "Success", "filled">;
	
	/**
	 * Heading field in *Callout → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: callout.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;
	
	/**
	 * Body field in *Callout → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: callout.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField;
}

/**
 * Default variation for Callout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Bordered callout box
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CalloutSliceDefault = prismic.SharedSliceVariation<"default", Simplify<CalloutSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Callout*
 */
type CalloutSliceVariation = CalloutSliceDefault

/**
 * Callout Shared Slice
 *
 * - **API ID**: `callout`
 * - **Description**: A bordered, colored box for a multi-line note/warning/highlighted block
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CalloutSlice = prismic.SharedSlice<"callout", CalloutSliceVariation>;

/**
 * Primary content in *CtaBanner → Default → Primary*
 */
export interface CtaBannerSliceDefaultPrimary {
	/**
	 * Body field in *CtaBanner → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_banner.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField;
	
	/**
	 * Label field in *CtaBanner → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_banner.default.primary.label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * Href field in *CtaBanner → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_banner.default.primary.href
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	href: prismic.KeyTextField;
}

/**
 * Default variation for CtaBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Call to action section for detail pages
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBannerSliceDefault = prismic.SharedSliceVariation<"default", Simplify<CtaBannerSliceDefaultPrimary>, never>;

/**
 * Slice variation for *CtaBanner*
 */
type CtaBannerSliceVariation = CtaBannerSliceDefault

/**
 * CtaBanner Shared Slice
 *
 * - **API ID**: `cta_banner`
 * - **Description**: Centered CTA button block
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBannerSlice = prismic.SharedSlice<"cta_banner", CtaBannerSliceVariation>;

/**
 * Primary content in *FaqQuestionList → Default → Primary*
 */
export interface FaqQuestionListSliceDefaultPrimary {
	/**
	 * Heading field in *FaqQuestionList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;
	
	/**
	 * Description field in *FaqQuestionList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * number field in *FaqQuestionList → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.default.primary.number
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	number: prismic.NumberField;
	
	/**
	 * text field in *FaqQuestionList → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	text: prismic.KeyTextField;
}

/**
 * Primary content in *FaqQuestionList → Items*
 */
export interface FaqQuestionListSliceDefaultItem {
	/**
	 * Question field in *FaqQuestionList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.items[].question
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	question: prismic.KeyTextField;
	
	/**
	 * Href field in *FaqQuestionList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.items[].href
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	href: prismic.KeyTextField;
}

/**
 * Default variation for FaqQuestionList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Category page list of FAQ questions
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqQuestionListSliceDefault = prismic.SharedSliceVariation<"default", Simplify<FaqQuestionListSliceDefaultPrimary>, Simplify<FaqQuestionListSliceDefaultItem>>;

/**
 * Primary content in *FaqQuestionList → grid → Primary*
 */
export interface FaqQuestionListSliceGridPrimary {
	/**
	 * Heading field in *FaqQuestionList → grid → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.grid.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;
	
	/**
	 * Description field in *FaqQuestionList → grid → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.grid.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
}

/**
 * Primary content in *FaqQuestionList → Items*
 */
export interface FaqQuestionListSliceGridItem {
	/**
	 * Question field in *FaqQuestionList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.items[].question
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	question: prismic.KeyTextField;
	
	/**
	 * Href field in *FaqQuestionList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.items[].href
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	href: prismic.KeyTextField;
}

/**
 * grid variation for FaqQuestionList Slice
 *
 * - **API ID**: `grid`
 * - **Description**: Category page list of FAQ questions
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqQuestionListSliceGrid = prismic.SharedSliceVariation<"grid", Simplify<FaqQuestionListSliceGridPrimary>, Simplify<FaqQuestionListSliceGridItem>>;

/**
 * Primary content in *FaqQuestionList → withicon → Primary*
 */
export interface FaqQuestionListSliceWithiconPrimary {
	/**
	 * Heading field in *FaqQuestionList → withicon → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.withicon.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;
	
	/**
	 * Description field in *FaqQuestionList → withicon → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.withicon.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
}

/**
 * Primary content in *FaqQuestionList → Items*
 */
export interface FaqQuestionListSliceWithiconItem {
	/**
	 * Question field in *FaqQuestionList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.items[].question
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	question: prismic.KeyTextField;
	
	/**
	 * Href field in *FaqQuestionList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.items[].href
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	href: prismic.KeyTextField;
}

/**
 * withicon variation for FaqQuestionList Slice
 *
 * - **API ID**: `withicon`
 * - **Description**: Category page list of FAQ questions
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqQuestionListSliceWithicon = prismic.SharedSliceVariation<"withicon", Simplify<FaqQuestionListSliceWithiconPrimary>, Simplify<FaqQuestionListSliceWithiconItem>>;

/**
 * Slice variation for *FaqQuestionList*
 */
type FaqQuestionListSliceVariation = FaqQuestionListSliceDefault | FaqQuestionListSliceGrid | FaqQuestionListSliceWithicon

/**
 * FaqQuestionList Shared Slice
 *
 * - **API ID**: `faq_question_list`
 * - **Description**: Question list with links to detail pages
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqQuestionListSlice = prismic.SharedSlice<"faq_question_list", FaqQuestionListSliceVariation>;

/**
 * Primary content in *HeroBanner → Default → Primary*
 */
export interface HeroBannerSliceDefaultPrimary {
	/**
	 * Title field in *HeroBanner → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_banner.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Image field in *HeroBanner → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_banner.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * CTA Label field in *HeroBanner → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_banner.default.primary.cta_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_label: prismic.KeyTextField;
	
	/**
	 * CTA Link field in *HeroBanner → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_banner.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for HeroBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroBannerSliceDefault = prismic.SharedSliceVariation<"default", Simplify<HeroBannerSliceDefaultPrimary>, never>;

/**
 * Slice variation for *HeroBanner*
 */
type HeroBannerSliceVariation = HeroBannerSliceDefault

/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: HeroBanner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroBannerSlice = prismic.SharedSlice<"hero_banner", HeroBannerSliceVariation>;

/**
 * Primary content in *ImageBlock → Default → Primary*
 */
export interface ImageBlockSliceDefaultPrimary {
	/**
	 * Image field in *ImageBlock → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_block.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Caption field in *ImageBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_block.default.primary.caption
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	caption: prismic.KeyTextField;
}

/**
 * Default variation for ImageBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Image with optional caption
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ImageBlockSliceDefaultPrimary>, never>;

/**
 * Slice variation for *ImageBlock*
 */
type ImageBlockSliceVariation = ImageBlockSliceDefault

/**
 * ImageBlock Shared Slice
 *
 * - **API ID**: `image_block`
 * - **Description**: A single image with an optional caption
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageBlockSlice = prismic.SharedSlice<"image_block", ImageBlockSliceVariation>;

/**
 * Primary content in *InfoCardList → Items*
 */
export interface InfoCardListSliceDefaultItem {
	/**
	 * Title field in *InfoCardList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: info_card_list.items[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Body field in *InfoCardList → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: info_card_list.items[].body
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField;
}

/**
 * Default variation for InfoCardList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Stacked info cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InfoCardListSliceDefault = prismic.SharedSliceVariation<"default", Record<string, never>, Simplify<InfoCardListSliceDefaultItem>>;

/**
 * Slice variation for *InfoCardList*
 */
type InfoCardListSliceVariation = InfoCardListSliceDefault

/**
 * InfoCardList Shared Slice
 *
 * - **API ID**: `info_card_list`
 * - **Description**: A list of bordered info cards, each with a title and body text
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InfoCardListSlice = prismic.SharedSlice<"info_card_list", InfoCardListSliceVariation>;

/**
 * Primary content in *NewsletterSignup → Default → Primary*
 */
export interface NewsletterSignupSliceDefaultPrimary {
	/**
	 * Title field in *NewsletterSignup → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: newsletter_signup.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Input Placeholder field in *NewsletterSignup → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: you@example.com
	 * - **API ID Path**: newsletter_signup.default.primary.input_placeholder
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	input_placeholder: prismic.KeyTextField;
	
	/**
	 * Submit Label field in *NewsletterSignup → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Subscribe
	 * - **API ID Path**: newsletter_signup.default.primary.submit_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	submit_label: prismic.KeyTextField;
}

/**
 * Default variation for NewsletterSignup Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsletterSignupSliceDefault = prismic.SharedSliceVariation<"default", Simplify<NewsletterSignupSliceDefaultPrimary>, never>;

/**
 * Slice variation for *NewsletterSignup*
 */
type NewsletterSignupSliceVariation = NewsletterSignupSliceDefault

/**
 * NewsletterSignup Shared Slice
 *
 * - **API ID**: `newsletter_signup`
 * - **Description**: NewsletterSignup
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsletterSignupSlice = prismic.SharedSlice<"newsletter_signup", NewsletterSignupSliceVariation>;

/**
 * Primary content in *PageTitle → Default → Primary*
 */
export interface PageTitleSliceDefaultPrimary {
	/**
	 * Title field in *PageTitle → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_title.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Subtitle field in *PageTitle → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_title.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;
}

/**
 * Default variation for PageTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PageTitleSliceDefault = prismic.SharedSliceVariation<"default", Simplify<PageTitleSliceDefaultPrimary>, never>;

/**
 * Slice variation for *PageTitle*
 */
type PageTitleSliceVariation = PageTitleSliceDefault

/**
 * PageTitle Shared Slice
 *
 * - **API ID**: `page_title`
 * - **Description**: PageTitle
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PageTitleSlice = prismic.SharedSlice<"page_title", PageTitleSliceVariation>;

/**
 * Primary content in *RichTextSection → Default → Primary*
 */
export interface RichTextSectionSliceDefaultPrimary {
	/**
	 * Heading field in *RichTextSection → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text_section.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;
	
	/**
	 * Body field in *RichTextSection → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text_section.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField;
	
	/**
	 * Font Size field in *RichTextSection → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Medium
	 * - **API ID Path**: rich_text_section.default.primary.font_size
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	font_size: prismic.SelectField<"Small" | "Medium" | "Large", "filled">;
	
	/**
	 * Font Color field in *RichTextSection → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Default
	 * - **API ID Path**: rich_text_section.default.primary.font_color
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	font_color: prismic.SelectField<"Default" | "Muted" | "Accent", "filled">;
}

/**
 * Primary content in *RichTextSection → Items*
 */
export interface RichTextSectionSliceDefaultItem {
	/**
	 * Line Text field in *RichTextSection → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text_section.items[].text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField;
	
	/**
	 * Font Size field in *RichTextSection → Items*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Medium
	 * - **API ID Path**: rich_text_section.items[].font_size
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	font_size: prismic.SelectField<"Small" | "Medium" | "Large", "filled">;
	
	/**
	 * Font Color field in *RichTextSection → Items*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Default
	 * - **API ID Path**: rich_text_section.items[].font_color
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	font_color: prismic.SelectField<"Default" | "Muted" | "Accent", "filled">;
}

/**
 * Default variation for RichTextSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Heading and body text
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSectionSliceDefault = prismic.SharedSliceVariation<"default", Simplify<RichTextSectionSliceDefaultPrimary>, Simplify<RichTextSectionSliceDefaultItem>>;

/**
 * Slice variation for *RichTextSection*
 */
type RichTextSectionSliceVariation = RichTextSectionSliceDefault

/**
 * RichTextSection Shared Slice
 *
 * - **API ID**: `rich_text_section`
 * - **Description**: Heading + body text block, optionally with inline links
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSectionSlice = prismic.SharedSlice<"rich_text_section", RichTextSectionSliceVariation>;

/**
 * Primary content in *SocialLinks → Default → Primary*
 */
export interface SocialLinksSliceDefaultPrimary {
	/**
	 * Title field in *SocialLinks → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: social_links.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
}

/**
 * Primary content in *SocialLinks → Items*
 */
export interface SocialLinksSliceDefaultItem {
	/**
	 * Label field in *SocialLinks → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: social_links.items[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * URL field in *SocialLinks → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: social_links.items[].url
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for SocialLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SocialLinksSliceDefault = prismic.SharedSliceVariation<"default", Simplify<SocialLinksSliceDefaultPrimary>, Simplify<SocialLinksSliceDefaultItem>>;

/**
 * Slice variation for *SocialLinks*
 */
type SocialLinksSliceVariation = SocialLinksSliceDefault

/**
 * SocialLinks Shared Slice
 *
 * - **API ID**: `social_links`
 * - **Description**: SocialLinks
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SocialLinksSlice = prismic.SharedSlice<"social_links", SocialLinksSliceVariation>;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
	}
	
	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			ContentPageDocument,
			ContentPageDocumentData,
			ContentPageDocumentDataHeadingSlice,
			ContentPageDocumentDataMainSlice,
			ContentPageDocumentDataAsideSlice,
			ContentPageDocumentDataFooterSlice,
			AllDocumentTypes,
			AccordionSlice,
			AccordionSliceDefaultItem,
			AccordionSliceVariation,
			AccordionSliceDefault,
			BreadcrumbsSlice,
			BreadcrumbsSliceDefaultPrimary,
			BreadcrumbsSliceVariation,
			BreadcrumbsSliceDefault,
			ButtonLinkSlice,
			ButtonLinkSliceDefaultPrimary,
			ButtonLinkSliceVariation,
			ButtonLinkSliceDefault,
			CalloutSlice,
			CalloutSliceDefaultPrimary,
			CalloutSliceVariation,
			CalloutSliceDefault,
			CtaBannerSlice,
			CtaBannerSliceDefaultPrimary,
			CtaBannerSliceVariation,
			CtaBannerSliceDefault,
			DisclosureListSlice,
			DisclosureListSliceDefaultItem,
			DisclosureListSliceVariation,
			DisclosureListSliceDefault,
			FaqQuestionListSlice,
			FaqQuestionListSliceDefaultPrimary,
			FaqQuestionListSliceDefaultItem,
			FaqQuestionListSliceGridPrimary,
			FaqQuestionListSliceGridItem,
			FaqQuestionListSliceWithiconPrimary,
			FaqQuestionListSliceWithiconItem,
			FaqQuestionListSliceVariation,
			FaqQuestionListSliceDefault,
			FaqQuestionListSliceGrid,
			FaqQuestionListSliceWithicon,
			FileDownloadListSlice,
			FileDownloadListSliceDefaultItem,
			FileDownloadListSliceVariation,
			FileDownloadListSliceDefault,
			HeroBannerSlice,
			HeroBannerSliceDefaultPrimary,
			HeroBannerSliceVariation,
			HeroBannerSliceDefault,
			ImageBlockSlice,
			ImageBlockSliceDefaultPrimary,
			ImageBlockSliceVariation,
			ImageBlockSliceDefault,
			InfoCardListSlice,
			InfoCardListSliceDefaultItem,
			InfoCardListSliceVariation,
			InfoCardListSliceDefault,
			NewsletterSignupSlice,
			NewsletterSignupSliceDefaultPrimary,
			NewsletterSignupSliceVariation,
			NewsletterSignupSliceDefault,
			PageTitleSlice,
			PageTitleSliceDefaultPrimary,
			PageTitleSliceVariation,
			PageTitleSliceDefault,
			RichTextSectionSlice,
			RichTextSectionSliceDefaultPrimary,
			RichTextSectionSliceDefaultItem,
			RichTextSectionSliceVariation,
			RichTextSectionSliceDefault,
			SocialLinksSlice,
			SocialLinksSliceDefaultPrimary,
			SocialLinksSliceDefaultItem,
			SocialLinksSliceVariation,
			SocialLinksSliceDefault
		}
	}
}