// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };


type PickContentRelationshipFieldData<
	TRelationship extends prismic.CustomTypeModelFetchCustomTypeLevel1 | prismic.CustomTypeModelFetchCustomTypeLevel2 | prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<string, prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone>,
	TLang extends string
> = |
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship["id"]]:
			ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
	} &
	// Group
	{
		[TGroup in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup["id"]]:
			TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
				? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
				: never
	} &
	// Other fields
	{
		[TFieldKey in Extract<TRelationship["fields"][number], string>]:
			TFieldKey extends keyof TData ? TData[TFieldKey] : never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[] | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>["id"]]:
		prismic.ContentRelationshipField<
			ID,
			TLang,
			PickContentRelationshipFieldData<
				Extract<TCustomType[number], { id: ID }>,
				Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
				TLang
			>
		>
}[Exclude<TCustomType[number], string>["id"]];

type ContentPageDocumentDataHeadingSlice = PageTitleSlice | BreadcrumbsSlice | HeroBannerSlice

type ContentPageDocumentDataMainSlice = CtaBannerSlice | FaqQuestionListSlice

type ContentPageDocumentDataAsideSlice = CtaBannerSlice | FaqQuestionListSlice

type ContentPageDocumentDataFooterSlice = NewsletterSignupSlice | SocialLinksSlice

/**
 * Content for Content Page documents
 */
interface ContentPageDocumentData {
	/**
	 * Breadcrumb Level 1 Label field in *Content Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_page.breadcrumb_level_1_label
	 * - **Tab**: Heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	breadcrumb_level_1_label: prismic.KeyTextField;
	
	/**
	 * Breadcrumb Level 1 Href field in *Content Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_page.breadcrumb_level_1_href
	 * - **Tab**: Heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	breadcrumb_level_1_href: prismic.KeyTextField;
	
	/**
	 * Breadcrumb Level 2 Label field in *Content Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_page.breadcrumb_level_2_label
	 * - **Tab**: Heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	breadcrumb_level_2_label: prismic.KeyTextField;
	
	/**
	 * Breadcrumb Level 2 Href field in *Content Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_page.breadcrumb_level_2_href
	 * - **Tab**: Heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	breadcrumb_level_2_href: prismic.KeyTextField;
	
	/**
	 * Breadcrumb Level 3 Label field in *Content Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_page.breadcrumb_level_3_label
	 * - **Tab**: Heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	breadcrumb_level_3_label: prismic.KeyTextField;
	
	/**
	 * Breadcrumb Level 3 Href field in *Content Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_page.breadcrumb_level_3_href
	 * - **Tab**: Heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	breadcrumb_level_3_href: prismic.KeyTextField;
	
	/**
	 * Heading Slice Zone field in *Content Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_page.heading[]
	 * - **Tab**: Heading
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	heading: prismic.SliceZone<ContentPageDocumentDataHeadingSlice>;/**
	 * Main Slice Zone field in *Content Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_page.main[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	main: prismic.SliceZone<ContentPageDocumentDataMainSlice>;/**
	 * Aside Slice Zone field in *Content Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_page.aside[]
	 * - **Tab**: Aside
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	aside: prismic.SliceZone<ContentPageDocumentDataAsideSlice>;/**
	 * Footer Slice Zone field in *Content Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_page.footer[]
	 * - **Tab**: Footer
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	footer: prismic.SliceZone<ContentPageDocumentDataFooterSlice>;
}

/**
 * Content Page document from Prismic
 *
 * - **API ID**: `content_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContentPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<ContentPageDocumentData>, "content_page", Lang>;

export type AllDocumentTypes = ContentPageDocument;

/**
 * Primary content in *Breadcrumbs → Default → Primary*
 */
export interface BreadcrumbsSliceDefaultPrimary {
	/**
	 * Separator field in *Breadcrumbs → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: /
	 * - **API ID Path**: breadcrumbs.default.primary.separator
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	separator: prismic.KeyTextField;
}

/**
 * Default variation for Breadcrumbs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BreadcrumbsSliceDefault = prismic.SharedSliceVariation<"default", Simplify<BreadcrumbsSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Breadcrumbs*
 */
type BreadcrumbsSliceVariation = BreadcrumbsSliceDefault

/**
 * Breadcrumbs Shared Slice
 *
 * - **API ID**: `breadcrumbs`
 * - **Description**: Breadcrumbs
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BreadcrumbsSlice = prismic.SharedSlice<"breadcrumbs", BreadcrumbsSliceVariation>;

/**
 * Primary content in *CtaBanner → Default → Primary*
 */
export interface CtaBannerSliceDefaultPrimary {
	/**
	 * Body field in *CtaBanner → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_banner.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField;
	
	/**
	 * Label field in *CtaBanner → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_banner.default.primary.label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * Href field in *CtaBanner → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_banner.default.primary.href
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	href: prismic.KeyTextField;
}

/**
 * Default variation for CtaBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Call to action section for detail pages
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBannerSliceDefault = prismic.SharedSliceVariation<"default", Simplify<CtaBannerSliceDefaultPrimary>, never>;

/**
 * Slice variation for *CtaBanner*
 */
type CtaBannerSliceVariation = CtaBannerSliceDefault

/**
 * CtaBanner Shared Slice
 *
 * - **API ID**: `cta_banner`
 * - **Description**: Centered CTA button block
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBannerSlice = prismic.SharedSlice<"cta_banner", CtaBannerSliceVariation>;

/**
 * Primary content in *FaqQuestionList → Default → Primary*
 */
export interface FaqQuestionListSliceDefaultPrimary {
	/**
	 * Heading field in *FaqQuestionList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;
	
	/**
	 * Description field in *FaqQuestionList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * number field in *FaqQuestionList → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.default.primary.number
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	number: prismic.NumberField;
	
	/**
	 * text field in *FaqQuestionList → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	text: prismic.KeyTextField;
}

/**
 * Primary content in *FaqQuestionList → Items*
 */
export interface FaqQuestionListSliceDefaultItem {
	/**
	 * Question field in *FaqQuestionList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.items[].question
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	question: prismic.KeyTextField;
	
	/**
	 * Href field in *FaqQuestionList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.items[].href
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	href: prismic.KeyTextField;
}

/**
 * Default variation for FaqQuestionList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Category page list of FAQ questions
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqQuestionListSliceDefault = prismic.SharedSliceVariation<"default", Simplify<FaqQuestionListSliceDefaultPrimary>, Simplify<FaqQuestionListSliceDefaultItem>>;

/**
 * Primary content in *FaqQuestionList → grid → Primary*
 */
export interface FaqQuestionListSliceGridPrimary {
	/**
	 * Heading field in *FaqQuestionList → grid → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.grid.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;
	
	/**
	 * Description field in *FaqQuestionList → grid → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.grid.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
}

/**
 * Primary content in *FaqQuestionList → Items*
 */
export interface FaqQuestionListSliceGridItem {
	/**
	 * Question field in *FaqQuestionList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.items[].question
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	question: prismic.KeyTextField;
	
	/**
	 * Href field in *FaqQuestionList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.items[].href
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	href: prismic.KeyTextField;
}

/**
 * grid variation for FaqQuestionList Slice
 *
 * - **API ID**: `grid`
 * - **Description**: Category page list of FAQ questions
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqQuestionListSliceGrid = prismic.SharedSliceVariation<"grid", Simplify<FaqQuestionListSliceGridPrimary>, Simplify<FaqQuestionListSliceGridItem>>;

/**
 * Primary content in *FaqQuestionList → withicon → Primary*
 */
export interface FaqQuestionListSliceWithiconPrimary {
	/**
	 * Heading field in *FaqQuestionList → withicon → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.withicon.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;
	
	/**
	 * Description field in *FaqQuestionList → withicon → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.withicon.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
}

/**
 * Primary content in *FaqQuestionList → Items*
 */
export interface FaqQuestionListSliceWithiconItem {
	/**
	 * Question field in *FaqQuestionList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.items[].question
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	question: prismic.KeyTextField;
	
	/**
	 * Href field in *FaqQuestionList → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_question_list.items[].href
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	href: prismic.KeyTextField;
}

/**
 * withicon variation for FaqQuestionList Slice
 *
 * - **API ID**: `withicon`
 * - **Description**: Category page list of FAQ questions
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqQuestionListSliceWithicon = prismic.SharedSliceVariation<"withicon", Simplify<FaqQuestionListSliceWithiconPrimary>, Simplify<FaqQuestionListSliceWithiconItem>>;

/**
 * Slice variation for *FaqQuestionList*
 */
type FaqQuestionListSliceVariation = FaqQuestionListSliceDefault | FaqQuestionListSliceGrid | FaqQuestionListSliceWithicon

/**
 * FaqQuestionList Shared Slice
 *
 * - **API ID**: `faq_question_list`
 * - **Description**: Question list with links to detail pages
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqQuestionListSlice = prismic.SharedSlice<"faq_question_list", FaqQuestionListSliceVariation>;

/**
 * Primary content in *HeroBanner → Default → Primary*
 */
export interface HeroBannerSliceDefaultPrimary {
	/**
	 * Title field in *HeroBanner → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_banner.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Image field in *HeroBanner → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_banner.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * CTA Label field in *HeroBanner → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_banner.default.primary.cta_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_label: prismic.KeyTextField;
	
	/**
	 * CTA Link field in *HeroBanner → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_banner.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for HeroBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroBannerSliceDefault = prismic.SharedSliceVariation<"default", Simplify<HeroBannerSliceDefaultPrimary>, never>;

/**
 * Slice variation for *HeroBanner*
 */
type HeroBannerSliceVariation = HeroBannerSliceDefault

/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: HeroBanner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroBannerSlice = prismic.SharedSlice<"hero_banner", HeroBannerSliceVariation>;

/**
 * Primary content in *NewsletterSignup → Default → Primary*
 */
export interface NewsletterSignupSliceDefaultPrimary {
	/**
	 * Title field in *NewsletterSignup → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: newsletter_signup.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Input Placeholder field in *NewsletterSignup → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: you@example.com
	 * - **API ID Path**: newsletter_signup.default.primary.input_placeholder
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	input_placeholder: prismic.KeyTextField;
	
	/**
	 * Submit Label field in *NewsletterSignup → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Subscribe
	 * - **API ID Path**: newsletter_signup.default.primary.submit_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	submit_label: prismic.KeyTextField;
}

/**
 * Default variation for NewsletterSignup Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsletterSignupSliceDefault = prismic.SharedSliceVariation<"default", Simplify<NewsletterSignupSliceDefaultPrimary>, never>;

/**
 * Slice variation for *NewsletterSignup*
 */
type NewsletterSignupSliceVariation = NewsletterSignupSliceDefault

/**
 * NewsletterSignup Shared Slice
 *
 * - **API ID**: `newsletter_signup`
 * - **Description**: NewsletterSignup
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsletterSignupSlice = prismic.SharedSlice<"newsletter_signup", NewsletterSignupSliceVariation>;

/**
 * Primary content in *PageTitle → Default → Primary*
 */
export interface PageTitleSliceDefaultPrimary {
	/**
	 * Title field in *PageTitle → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_title.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Subtitle field in *PageTitle → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_title.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;
}

/**
 * Default variation for PageTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PageTitleSliceDefault = prismic.SharedSliceVariation<"default", Simplify<PageTitleSliceDefaultPrimary>, never>;

/**
 * Slice variation for *PageTitle*
 */
type PageTitleSliceVariation = PageTitleSliceDefault

/**
 * PageTitle Shared Slice
 *
 * - **API ID**: `page_title`
 * - **Description**: PageTitle
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PageTitleSlice = prismic.SharedSlice<"page_title", PageTitleSliceVariation>;

/**
 * Primary content in *SocialLinks → Default → Primary*
 */
export interface SocialLinksSliceDefaultPrimary {
	/**
	 * Title field in *SocialLinks → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: social_links.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
}

/**
 * Primary content in *SocialLinks → Items*
 */
export interface SocialLinksSliceDefaultItem {
	/**
	 * Label field in *SocialLinks → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: social_links.items[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * URL field in *SocialLinks → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: social_links.items[].url
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for SocialLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SocialLinksSliceDefault = prismic.SharedSliceVariation<"default", Simplify<SocialLinksSliceDefaultPrimary>, Simplify<SocialLinksSliceDefaultItem>>;

/**
 * Slice variation for *SocialLinks*
 */
type SocialLinksSliceVariation = SocialLinksSliceDefault

/**
 * SocialLinks Shared Slice
 *
 * - **API ID**: `social_links`
 * - **Description**: SocialLinks
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SocialLinksSlice = prismic.SharedSlice<"social_links", SocialLinksSliceVariation>;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
	}
	
	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			ContentPageDocument,
			ContentPageDocumentData,
			ContentPageDocumentDataHeadingSlice,
			ContentPageDocumentDataMainSlice,
			ContentPageDocumentDataAsideSlice,
			ContentPageDocumentDataFooterSlice,
			AllDocumentTypes,
			BreadcrumbsSlice,
			BreadcrumbsSliceDefaultPrimary,
			BreadcrumbsSliceVariation,
			BreadcrumbsSliceDefault,
			CtaBannerSlice,
			CtaBannerSliceDefaultPrimary,
			CtaBannerSliceVariation,
			CtaBannerSliceDefault,
			FaqQuestionListSlice,
			FaqQuestionListSliceDefaultPrimary,
			FaqQuestionListSliceDefaultItem,
			FaqQuestionListSliceGridPrimary,
			FaqQuestionListSliceGridItem,
			FaqQuestionListSliceWithiconPrimary,
			FaqQuestionListSliceWithiconItem,
			FaqQuestionListSliceVariation,
			FaqQuestionListSliceDefault,
			FaqQuestionListSliceGrid,
			FaqQuestionListSliceWithicon,
			HeroBannerSlice,
			HeroBannerSliceDefaultPrimary,
			HeroBannerSliceVariation,
			HeroBannerSliceDefault,
			NewsletterSignupSlice,
			NewsletterSignupSliceDefaultPrimary,
			NewsletterSignupSliceVariation,
			NewsletterSignupSliceDefault,
			PageTitleSlice,
			PageTitleSliceDefaultPrimary,
			PageTitleSliceVariation,
			PageTitleSliceDefault,
			SocialLinksSlice,
			SocialLinksSliceDefaultPrimary,
			SocialLinksSliceDefaultItem,
			SocialLinksSliceVariation,
			SocialLinksSliceDefault
		}
	}
}