name: next-cms App

on:
  pull_request:
  push:
    branches: [master]

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      app_name: next-cms
      app_path: .
    secrets:
      NEXUZ_SNYK_TOKEN: ${{ secrets.NEXUZ_SNYK_TOKEN }}
      ACCESSIBILITY_API_KEY: ${{ secrets.ACCESSIBILITY_API_KEY }}
      PRISMIC_ACCESS_TOKEN: ${{ secrets.PRISMIC_ACCESS_TOKEN }}
